// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

public final class HRDepartmentServiceImpl {
  private HRDepartmentServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_WeeklyWorkingHourRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_WeeklyWorkingHourRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_WeeklyWorkingHourResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_WeeklyWorkingHourResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_Monthly_Payroll_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_Monthly_Payroll_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_Monthly_Payroll_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_Monthly_Payroll_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031HRDepartmentService.proto\022\016office_serv" +
      "ice\"\261\001\n\030WeeklyWorkingHourRequest\022\033\n\023mond" +
      "ay_working_hour\030\001 \001(\005\022\034\n\024tuesday_working" +
      "_hour\030\002 \001(\005\022\036\n\026wednesday_working_hour\030\003 " +
      "\001(\005\022\035\n\025thursday_working_hour\030\004 \001(\005\022\033\n\023fr" +
      "iday_working_hour\030\005 \001(\005\"c\n\031WeeklyWorking" +
      "HourResponse\022!\n\031total_weekly_working_hou" +
      "r\030\001 \001(\005\022#\n\033weekly_working_hour_message\030\002" +
      " \001(\t\"w\n\027Monthly_Payroll_Request\022\033\n\023norma" +
      "l_working_hour\030\001 \001(\005\022 \n\030holiday_pay_work" +
      "ing_hour\030\002 \001(\005\022\035\n\025overtime_working_hour\030" +
      "\003 \001(\005\";\n\030Monthly_Payroll_Response\022\037\n\027mon" +
      "thly_payroll_message\030\001 \001(\t2\332\001\n\023HRDepartm" +
      "entService\022`\n\005check\022(.office_service.Wee" +
      "klyWorkingHourRequest\032).office_service.W" +
      "eeklyWorkingHourResponse(\0010\001\022a\n\ninput_ho" +
      "ur\022\'.office_service.Monthly_Payroll_Requ" +
      "est\032(.office_service.Monthly_Payroll_Res" +
      "ponse(\001B@\n#grpc.services.hr_department_s" +
      "erviceB\027HRDepartmentServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_service_WeeklyWorkingHourRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_service_WeeklyWorkingHourRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_WeeklyWorkingHourRequest_descriptor,
        new java.lang.String[] { "MondayWorkingHour", "TuesdayWorkingHour", "WednesdayWorkingHour", "ThursdayWorkingHour", "FridayWorkingHour", });
    internal_static_office_service_WeeklyWorkingHourResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_service_WeeklyWorkingHourResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_WeeklyWorkingHourResponse_descriptor,
        new java.lang.String[] { "TotalWeeklyWorkingHour", "WeeklyWorkingHourMessage", });
    internal_static_office_service_Monthly_Payroll_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_office_service_Monthly_Payroll_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_Monthly_Payroll_Request_descriptor,
        new java.lang.String[] { "NormalWorkingHour", "HolidayPayWorkingHour", "OvertimeWorkingHour", });
    internal_static_office_service_Monthly_Payroll_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_office_service_Monthly_Payroll_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_Monthly_Payroll_Response_descriptor,
        new java.lang.String[] { "MonthlyPayrollMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
