// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

public final class HRDepartmentServiceImpl {
  private HRDepartmentServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_WeeklyWorkingHourRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_WeeklyWorkingHourRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_WeeklyWorkingHourResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_WeeklyWorkingHourResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_Monthly_Payroll_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_Monthly_Payroll_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_Monthly_Payroll_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_Monthly_Payroll_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031HRDepartmentService.proto\022\016office_serv" +
      "ice\"\303\001\n\030WeeklyWorkingHourRequest\022\033\n\023mond" +
      "ay_working_hour\030\001 \001(\001\022\034\n\024tuesday_working" +
      "_hour\030\002 \001(\001\022\036\n\026wednesday_working_hour\030\003 " +
      "\001(\001\022\035\n\025thursday_working_hour\030\004 \001(\001\022\033\n\023fr" +
      "iday_working_hour\030\005 \001(\001\022\020\n\010dayCount\030\006 \001(" +
      "\005\"c\n\031WeeklyWorkingHourResponse\022!\n\031total_" +
      "weekly_working_hour\030\001 \001(\001\022#\n\033weekly_work" +
      "ing_hour_message\030\002 \001(\t\"w\n\027Monthly_Payrol" +
      "l_Request\022\033\n\023normal_working_hour\030\001 \001(\005\022 " +
      "\n\030holiday_pay_working_hour\030\002 \001(\005\022\035\n\025over" +
      "time_working_hour\030\003 \001(\005\";\n\030Monthly_Payro" +
      "ll_Response\022\037\n\027monthly_payroll_message\030\001" +
      " \001(\t2\331\001\n\023HRDepartmentService\022`\n\005check\022(." +
      "office_service.WeeklyWorkingHourRequest\032" +
      ").office_service.WeeklyWorkingHourRespon" +
      "se(\0010\001\022`\n\tinputHour\022\'.office_service.Mon" +
      "thly_Payroll_Request\032(.office_service.Mo" +
      "nthly_Payroll_Response(\001B@\n#grpc.service" +
      "s.hr_department_serviceB\027HRDepartmentSer" +
      "viceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_service_WeeklyWorkingHourRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_service_WeeklyWorkingHourRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_WeeklyWorkingHourRequest_descriptor,
        new java.lang.String[] { "MondayWorkingHour", "TuesdayWorkingHour", "WednesdayWorkingHour", "ThursdayWorkingHour", "FridayWorkingHour", "DayCount", });
    internal_static_office_service_WeeklyWorkingHourResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_service_WeeklyWorkingHourResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_WeeklyWorkingHourResponse_descriptor,
        new java.lang.String[] { "TotalWeeklyWorkingHour", "WeeklyWorkingHourMessage", });
    internal_static_office_service_Monthly_Payroll_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_office_service_Monthly_Payroll_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_Monthly_Payroll_Request_descriptor,
        new java.lang.String[] { "NormalWorkingHour", "HolidayPayWorkingHour", "OvertimeWorkingHour", });
    internal_static_office_service_Monthly_Payroll_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_office_service_Monthly_Payroll_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_Monthly_Payroll_Response_descriptor,
        new java.lang.String[] { "MonthlyPayrollMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
