// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

/**
 * Protobuf type {@code office_service.Monthly_Payroll_Response}
 */
public  final class Monthly_Payroll_Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:office_service.Monthly_Payroll_Response)
    Monthly_Payroll_ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Monthly_Payroll_Response.newBuilder() to construct.
  private Monthly_Payroll_Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Monthly_Payroll_Response() {
    monthlyPayrollMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Monthly_Payroll_Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            monthlyPayrollMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.hr_department_service.Monthly_Payroll_Response.class, grpc.services.hr_department_service.Monthly_Payroll_Response.Builder.class);
  }

  public static final int MONTHLY_PAYROLL_MESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object monthlyPayrollMessage_;
  /**
   * <code>string monthly_payroll_message = 1;</code>
   */
  public java.lang.String getMonthlyPayrollMessage() {
    java.lang.Object ref = monthlyPayrollMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      monthlyPayrollMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string monthly_payroll_message = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMonthlyPayrollMessageBytes() {
    java.lang.Object ref = monthlyPayrollMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      monthlyPayrollMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMonthlyPayrollMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, monthlyPayrollMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMonthlyPayrollMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, monthlyPayrollMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.hr_department_service.Monthly_Payroll_Response)) {
      return super.equals(obj);
    }
    grpc.services.hr_department_service.Monthly_Payroll_Response other = (grpc.services.hr_department_service.Monthly_Payroll_Response) obj;

    boolean result = true;
    result = result && getMonthlyPayrollMessage()
        .equals(other.getMonthlyPayrollMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MONTHLY_PAYROLL_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMonthlyPayrollMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.hr_department_service.Monthly_Payroll_Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code office_service.Monthly_Payroll_Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:office_service.Monthly_Payroll_Response)
      grpc.services.hr_department_service.Monthly_Payroll_ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.hr_department_service.Monthly_Payroll_Response.class, grpc.services.hr_department_service.Monthly_Payroll_Response.Builder.class);
    }

    // Construct using grpc.services.hr_department_service.Monthly_Payroll_Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      monthlyPayrollMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Response_descriptor;
    }

    @java.lang.Override
    public grpc.services.hr_department_service.Monthly_Payroll_Response getDefaultInstanceForType() {
      return grpc.services.hr_department_service.Monthly_Payroll_Response.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.hr_department_service.Monthly_Payroll_Response build() {
      grpc.services.hr_department_service.Monthly_Payroll_Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.hr_department_service.Monthly_Payroll_Response buildPartial() {
      grpc.services.hr_department_service.Monthly_Payroll_Response result = new grpc.services.hr_department_service.Monthly_Payroll_Response(this);
      result.monthlyPayrollMessage_ = monthlyPayrollMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.hr_department_service.Monthly_Payroll_Response) {
        return mergeFrom((grpc.services.hr_department_service.Monthly_Payroll_Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.hr_department_service.Monthly_Payroll_Response other) {
      if (other == grpc.services.hr_department_service.Monthly_Payroll_Response.getDefaultInstance()) return this;
      if (!other.getMonthlyPayrollMessage().isEmpty()) {
        monthlyPayrollMessage_ = other.monthlyPayrollMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.hr_department_service.Monthly_Payroll_Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.hr_department_service.Monthly_Payroll_Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object monthlyPayrollMessage_ = "";
    /**
     * <code>string monthly_payroll_message = 1;</code>
     */
    public java.lang.String getMonthlyPayrollMessage() {
      java.lang.Object ref = monthlyPayrollMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        monthlyPayrollMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string monthly_payroll_message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMonthlyPayrollMessageBytes() {
      java.lang.Object ref = monthlyPayrollMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        monthlyPayrollMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string monthly_payroll_message = 1;</code>
     */
    public Builder setMonthlyPayrollMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      monthlyPayrollMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string monthly_payroll_message = 1;</code>
     */
    public Builder clearMonthlyPayrollMessage() {
      
      monthlyPayrollMessage_ = getDefaultInstance().getMonthlyPayrollMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string monthly_payroll_message = 1;</code>
     */
    public Builder setMonthlyPayrollMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      monthlyPayrollMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:office_service.Monthly_Payroll_Response)
  }

  // @@protoc_insertion_point(class_scope:office_service.Monthly_Payroll_Response)
  private static final grpc.services.hr_department_service.Monthly_Payroll_Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.hr_department_service.Monthly_Payroll_Response();
  }

  public static grpc.services.hr_department_service.Monthly_Payroll_Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Monthly_Payroll_Response>
      PARSER = new com.google.protobuf.AbstractParser<Monthly_Payroll_Response>() {
    @java.lang.Override
    public Monthly_Payroll_Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Monthly_Payroll_Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Monthly_Payroll_Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Monthly_Payroll_Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.hr_department_service.Monthly_Payroll_Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

