// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

public interface Monthly_Payroll_ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.Monthly_Payroll_Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string monthly_payroll_message = 1;</code>
   */
  java.lang.String getMonthlyPayrollMessage();
  /**
   * <code>string monthly_payroll_message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMonthlyPayrollMessageBytes();
}
