// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

/**
 * Protobuf type {@code office_service.Monthly_Payroll_Request}
 */
public  final class Monthly_Payroll_Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:office_service.Monthly_Payroll_Request)
    Monthly_Payroll_RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Monthly_Payroll_Request.newBuilder() to construct.
  private Monthly_Payroll_Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Monthly_Payroll_Request() {
    normalWorkingHour_ = 0;
    holidayPayWorkingHour_ = 0;
    overtimeWorkingHour_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Monthly_Payroll_Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            normalWorkingHour_ = input.readInt32();
            break;
          }
          case 16: {

            holidayPayWorkingHour_ = input.readInt32();
            break;
          }
          case 24: {

            overtimeWorkingHour_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.hr_department_service.Monthly_Payroll_Request.class, grpc.services.hr_department_service.Monthly_Payroll_Request.Builder.class);
  }

  public static final int NORMAL_WORKING_HOUR_FIELD_NUMBER = 1;
  private int normalWorkingHour_;
  /**
   * <code>int32 normal_working_hour = 1;</code>
   */
  public int getNormalWorkingHour() {
    return normalWorkingHour_;
  }

  public static final int HOLIDAY_PAY_WORKING_HOUR_FIELD_NUMBER = 2;
  private int holidayPayWorkingHour_;
  /**
   * <code>int32 holiday_pay_working_hour = 2;</code>
   */
  public int getHolidayPayWorkingHour() {
    return holidayPayWorkingHour_;
  }

  public static final int OVERTIME_WORKING_HOUR_FIELD_NUMBER = 3;
  private int overtimeWorkingHour_;
  /**
   * <code>int32 overtime_working_hour = 3;</code>
   */
  public int getOvertimeWorkingHour() {
    return overtimeWorkingHour_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (normalWorkingHour_ != 0) {
      output.writeInt32(1, normalWorkingHour_);
    }
    if (holidayPayWorkingHour_ != 0) {
      output.writeInt32(2, holidayPayWorkingHour_);
    }
    if (overtimeWorkingHour_ != 0) {
      output.writeInt32(3, overtimeWorkingHour_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (normalWorkingHour_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, normalWorkingHour_);
    }
    if (holidayPayWorkingHour_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, holidayPayWorkingHour_);
    }
    if (overtimeWorkingHour_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, overtimeWorkingHour_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.hr_department_service.Monthly_Payroll_Request)) {
      return super.equals(obj);
    }
    grpc.services.hr_department_service.Monthly_Payroll_Request other = (grpc.services.hr_department_service.Monthly_Payroll_Request) obj;

    boolean result = true;
    result = result && (getNormalWorkingHour()
        == other.getNormalWorkingHour());
    result = result && (getHolidayPayWorkingHour()
        == other.getHolidayPayWorkingHour());
    result = result && (getOvertimeWorkingHour()
        == other.getOvertimeWorkingHour());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NORMAL_WORKING_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + getNormalWorkingHour();
    hash = (37 * hash) + HOLIDAY_PAY_WORKING_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + getHolidayPayWorkingHour();
    hash = (37 * hash) + OVERTIME_WORKING_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + getOvertimeWorkingHour();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.Monthly_Payroll_Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.hr_department_service.Monthly_Payroll_Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code office_service.Monthly_Payroll_Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:office_service.Monthly_Payroll_Request)
      grpc.services.hr_department_service.Monthly_Payroll_RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.hr_department_service.Monthly_Payroll_Request.class, grpc.services.hr_department_service.Monthly_Payroll_Request.Builder.class);
    }

    // Construct using grpc.services.hr_department_service.Monthly_Payroll_Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      normalWorkingHour_ = 0;

      holidayPayWorkingHour_ = 0;

      overtimeWorkingHour_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_Monthly_Payroll_Request_descriptor;
    }

    @java.lang.Override
    public grpc.services.hr_department_service.Monthly_Payroll_Request getDefaultInstanceForType() {
      return grpc.services.hr_department_service.Monthly_Payroll_Request.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.hr_department_service.Monthly_Payroll_Request build() {
      grpc.services.hr_department_service.Monthly_Payroll_Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.hr_department_service.Monthly_Payroll_Request buildPartial() {
      grpc.services.hr_department_service.Monthly_Payroll_Request result = new grpc.services.hr_department_service.Monthly_Payroll_Request(this);
      result.normalWorkingHour_ = normalWorkingHour_;
      result.holidayPayWorkingHour_ = holidayPayWorkingHour_;
      result.overtimeWorkingHour_ = overtimeWorkingHour_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.hr_department_service.Monthly_Payroll_Request) {
        return mergeFrom((grpc.services.hr_department_service.Monthly_Payroll_Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.hr_department_service.Monthly_Payroll_Request other) {
      if (other == grpc.services.hr_department_service.Monthly_Payroll_Request.getDefaultInstance()) return this;
      if (other.getNormalWorkingHour() != 0) {
        setNormalWorkingHour(other.getNormalWorkingHour());
      }
      if (other.getHolidayPayWorkingHour() != 0) {
        setHolidayPayWorkingHour(other.getHolidayPayWorkingHour());
      }
      if (other.getOvertimeWorkingHour() != 0) {
        setOvertimeWorkingHour(other.getOvertimeWorkingHour());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.hr_department_service.Monthly_Payroll_Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.hr_department_service.Monthly_Payroll_Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int normalWorkingHour_ ;
    /**
     * <code>int32 normal_working_hour = 1;</code>
     */
    public int getNormalWorkingHour() {
      return normalWorkingHour_;
    }
    /**
     * <code>int32 normal_working_hour = 1;</code>
     */
    public Builder setNormalWorkingHour(int value) {
      
      normalWorkingHour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 normal_working_hour = 1;</code>
     */
    public Builder clearNormalWorkingHour() {
      
      normalWorkingHour_ = 0;
      onChanged();
      return this;
    }

    private int holidayPayWorkingHour_ ;
    /**
     * <code>int32 holiday_pay_working_hour = 2;</code>
     */
    public int getHolidayPayWorkingHour() {
      return holidayPayWorkingHour_;
    }
    /**
     * <code>int32 holiday_pay_working_hour = 2;</code>
     */
    public Builder setHolidayPayWorkingHour(int value) {
      
      holidayPayWorkingHour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 holiday_pay_working_hour = 2;</code>
     */
    public Builder clearHolidayPayWorkingHour() {
      
      holidayPayWorkingHour_ = 0;
      onChanged();
      return this;
    }

    private int overtimeWorkingHour_ ;
    /**
     * <code>int32 overtime_working_hour = 3;</code>
     */
    public int getOvertimeWorkingHour() {
      return overtimeWorkingHour_;
    }
    /**
     * <code>int32 overtime_working_hour = 3;</code>
     */
    public Builder setOvertimeWorkingHour(int value) {
      
      overtimeWorkingHour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 overtime_working_hour = 3;</code>
     */
    public Builder clearOvertimeWorkingHour() {
      
      overtimeWorkingHour_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:office_service.Monthly_Payroll_Request)
  }

  // @@protoc_insertion_point(class_scope:office_service.Monthly_Payroll_Request)
  private static final grpc.services.hr_department_service.Monthly_Payroll_Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.hr_department_service.Monthly_Payroll_Request();
  }

  public static grpc.services.hr_department_service.Monthly_Payroll_Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Monthly_Payroll_Request>
      PARSER = new com.google.protobuf.AbstractParser<Monthly_Payroll_Request>() {
    @java.lang.Override
    public Monthly_Payroll_Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Monthly_Payroll_Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Monthly_Payroll_Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Monthly_Payroll_Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.hr_department_service.Monthly_Payroll_Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

