// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

public interface WeeklyWorkingHourRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.WeeklyWorkingHourRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double monday_working_hour = 1;</code>
   */
  double getMondayWorkingHour();

  /**
   * <code>double tuesday_working_hour = 2;</code>
   */
  double getTuesdayWorkingHour();

  /**
   * <code>double wednesday_working_hour = 3;</code>
   */
  double getWednesdayWorkingHour();

  /**
   * <code>double thursday_working_hour = 4;</code>
   */
  double getThursdayWorkingHour();

  /**
   * <code>double friday_working_hour = 5;</code>
   */
  double getFridayWorkingHour();

  /**
   * <code>int32 dayCount = 6;</code>
   */
  int getDayCount();
}
