// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

/**
 * Protobuf type {@code office_service.WeeklyWorkingHourRequest}
 */
public  final class WeeklyWorkingHourRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:office_service.WeeklyWorkingHourRequest)
    WeeklyWorkingHourRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeeklyWorkingHourRequest.newBuilder() to construct.
  private WeeklyWorkingHourRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeeklyWorkingHourRequest() {
    mondayWorkingHour_ = 0D;
    tuesdayWorkingHour_ = 0D;
    wednesdayWorkingHour_ = 0D;
    thursdayWorkingHour_ = 0D;
    fridayWorkingHour_ = 0D;
    dayCount_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeeklyWorkingHourRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            mondayWorkingHour_ = input.readDouble();
            break;
          }
          case 17: {

            tuesdayWorkingHour_ = input.readDouble();
            break;
          }
          case 25: {

            wednesdayWorkingHour_ = input.readDouble();
            break;
          }
          case 33: {

            thursdayWorkingHour_ = input.readDouble();
            break;
          }
          case 41: {

            fridayWorkingHour_ = input.readDouble();
            break;
          }
          case 48: {

            dayCount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.hr_department_service.WeeklyWorkingHourRequest.class, grpc.services.hr_department_service.WeeklyWorkingHourRequest.Builder.class);
  }

  public static final int MONDAY_WORKING_HOUR_FIELD_NUMBER = 1;
  private double mondayWorkingHour_;
  /**
   * <code>double monday_working_hour = 1;</code>
   */
  public double getMondayWorkingHour() {
    return mondayWorkingHour_;
  }

  public static final int TUESDAY_WORKING_HOUR_FIELD_NUMBER = 2;
  private double tuesdayWorkingHour_;
  /**
   * <code>double tuesday_working_hour = 2;</code>
   */
  public double getTuesdayWorkingHour() {
    return tuesdayWorkingHour_;
  }

  public static final int WEDNESDAY_WORKING_HOUR_FIELD_NUMBER = 3;
  private double wednesdayWorkingHour_;
  /**
   * <code>double wednesday_working_hour = 3;</code>
   */
  public double getWednesdayWorkingHour() {
    return wednesdayWorkingHour_;
  }

  public static final int THURSDAY_WORKING_HOUR_FIELD_NUMBER = 4;
  private double thursdayWorkingHour_;
  /**
   * <code>double thursday_working_hour = 4;</code>
   */
  public double getThursdayWorkingHour() {
    return thursdayWorkingHour_;
  }

  public static final int FRIDAY_WORKING_HOUR_FIELD_NUMBER = 5;
  private double fridayWorkingHour_;
  /**
   * <code>double friday_working_hour = 5;</code>
   */
  public double getFridayWorkingHour() {
    return fridayWorkingHour_;
  }

  public static final int DAYCOUNT_FIELD_NUMBER = 6;
  private int dayCount_;
  /**
   * <code>int32 dayCount = 6;</code>
   */
  public int getDayCount() {
    return dayCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mondayWorkingHour_ != 0D) {
      output.writeDouble(1, mondayWorkingHour_);
    }
    if (tuesdayWorkingHour_ != 0D) {
      output.writeDouble(2, tuesdayWorkingHour_);
    }
    if (wednesdayWorkingHour_ != 0D) {
      output.writeDouble(3, wednesdayWorkingHour_);
    }
    if (thursdayWorkingHour_ != 0D) {
      output.writeDouble(4, thursdayWorkingHour_);
    }
    if (fridayWorkingHour_ != 0D) {
      output.writeDouble(5, fridayWorkingHour_);
    }
    if (dayCount_ != 0) {
      output.writeInt32(6, dayCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mondayWorkingHour_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, mondayWorkingHour_);
    }
    if (tuesdayWorkingHour_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, tuesdayWorkingHour_);
    }
    if (wednesdayWorkingHour_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, wednesdayWorkingHour_);
    }
    if (thursdayWorkingHour_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, thursdayWorkingHour_);
    }
    if (fridayWorkingHour_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, fridayWorkingHour_);
    }
    if (dayCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, dayCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.hr_department_service.WeeklyWorkingHourRequest)) {
      return super.equals(obj);
    }
    grpc.services.hr_department_service.WeeklyWorkingHourRequest other = (grpc.services.hr_department_service.WeeklyWorkingHourRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getMondayWorkingHour())
        == java.lang.Double.doubleToLongBits(
            other.getMondayWorkingHour()));
    result = result && (
        java.lang.Double.doubleToLongBits(getTuesdayWorkingHour())
        == java.lang.Double.doubleToLongBits(
            other.getTuesdayWorkingHour()));
    result = result && (
        java.lang.Double.doubleToLongBits(getWednesdayWorkingHour())
        == java.lang.Double.doubleToLongBits(
            other.getWednesdayWorkingHour()));
    result = result && (
        java.lang.Double.doubleToLongBits(getThursdayWorkingHour())
        == java.lang.Double.doubleToLongBits(
            other.getThursdayWorkingHour()));
    result = result && (
        java.lang.Double.doubleToLongBits(getFridayWorkingHour())
        == java.lang.Double.doubleToLongBits(
            other.getFridayWorkingHour()));
    result = result && (getDayCount()
        == other.getDayCount());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MONDAY_WORKING_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMondayWorkingHour()));
    hash = (37 * hash) + TUESDAY_WORKING_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTuesdayWorkingHour()));
    hash = (37 * hash) + WEDNESDAY_WORKING_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWednesdayWorkingHour()));
    hash = (37 * hash) + THURSDAY_WORKING_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getThursdayWorkingHour()));
    hash = (37 * hash) + FRIDAY_WORKING_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFridayWorkingHour()));
    hash = (37 * hash) + DAYCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getDayCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.hr_department_service.WeeklyWorkingHourRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code office_service.WeeklyWorkingHourRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:office_service.WeeklyWorkingHourRequest)
      grpc.services.hr_department_service.WeeklyWorkingHourRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.hr_department_service.WeeklyWorkingHourRequest.class, grpc.services.hr_department_service.WeeklyWorkingHourRequest.Builder.class);
    }

    // Construct using grpc.services.hr_department_service.WeeklyWorkingHourRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mondayWorkingHour_ = 0D;

      tuesdayWorkingHour_ = 0D;

      wednesdayWorkingHour_ = 0D;

      thursdayWorkingHour_ = 0D;

      fridayWorkingHour_ = 0D;

      dayCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourRequest_descriptor;
    }

    @java.lang.Override
    public grpc.services.hr_department_service.WeeklyWorkingHourRequest getDefaultInstanceForType() {
      return grpc.services.hr_department_service.WeeklyWorkingHourRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.hr_department_service.WeeklyWorkingHourRequest build() {
      grpc.services.hr_department_service.WeeklyWorkingHourRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.hr_department_service.WeeklyWorkingHourRequest buildPartial() {
      grpc.services.hr_department_service.WeeklyWorkingHourRequest result = new grpc.services.hr_department_service.WeeklyWorkingHourRequest(this);
      result.mondayWorkingHour_ = mondayWorkingHour_;
      result.tuesdayWorkingHour_ = tuesdayWorkingHour_;
      result.wednesdayWorkingHour_ = wednesdayWorkingHour_;
      result.thursdayWorkingHour_ = thursdayWorkingHour_;
      result.fridayWorkingHour_ = fridayWorkingHour_;
      result.dayCount_ = dayCount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.hr_department_service.WeeklyWorkingHourRequest) {
        return mergeFrom((grpc.services.hr_department_service.WeeklyWorkingHourRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.hr_department_service.WeeklyWorkingHourRequest other) {
      if (other == grpc.services.hr_department_service.WeeklyWorkingHourRequest.getDefaultInstance()) return this;
      if (other.getMondayWorkingHour() != 0D) {
        setMondayWorkingHour(other.getMondayWorkingHour());
      }
      if (other.getTuesdayWorkingHour() != 0D) {
        setTuesdayWorkingHour(other.getTuesdayWorkingHour());
      }
      if (other.getWednesdayWorkingHour() != 0D) {
        setWednesdayWorkingHour(other.getWednesdayWorkingHour());
      }
      if (other.getThursdayWorkingHour() != 0D) {
        setThursdayWorkingHour(other.getThursdayWorkingHour());
      }
      if (other.getFridayWorkingHour() != 0D) {
        setFridayWorkingHour(other.getFridayWorkingHour());
      }
      if (other.getDayCount() != 0) {
        setDayCount(other.getDayCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.hr_department_service.WeeklyWorkingHourRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.hr_department_service.WeeklyWorkingHourRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double mondayWorkingHour_ ;
    /**
     * <code>double monday_working_hour = 1;</code>
     */
    public double getMondayWorkingHour() {
      return mondayWorkingHour_;
    }
    /**
     * <code>double monday_working_hour = 1;</code>
     */
    public Builder setMondayWorkingHour(double value) {
      
      mondayWorkingHour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double monday_working_hour = 1;</code>
     */
    public Builder clearMondayWorkingHour() {
      
      mondayWorkingHour_ = 0D;
      onChanged();
      return this;
    }

    private double tuesdayWorkingHour_ ;
    /**
     * <code>double tuesday_working_hour = 2;</code>
     */
    public double getTuesdayWorkingHour() {
      return tuesdayWorkingHour_;
    }
    /**
     * <code>double tuesday_working_hour = 2;</code>
     */
    public Builder setTuesdayWorkingHour(double value) {
      
      tuesdayWorkingHour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double tuesday_working_hour = 2;</code>
     */
    public Builder clearTuesdayWorkingHour() {
      
      tuesdayWorkingHour_ = 0D;
      onChanged();
      return this;
    }

    private double wednesdayWorkingHour_ ;
    /**
     * <code>double wednesday_working_hour = 3;</code>
     */
    public double getWednesdayWorkingHour() {
      return wednesdayWorkingHour_;
    }
    /**
     * <code>double wednesday_working_hour = 3;</code>
     */
    public Builder setWednesdayWorkingHour(double value) {
      
      wednesdayWorkingHour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double wednesday_working_hour = 3;</code>
     */
    public Builder clearWednesdayWorkingHour() {
      
      wednesdayWorkingHour_ = 0D;
      onChanged();
      return this;
    }

    private double thursdayWorkingHour_ ;
    /**
     * <code>double thursday_working_hour = 4;</code>
     */
    public double getThursdayWorkingHour() {
      return thursdayWorkingHour_;
    }
    /**
     * <code>double thursday_working_hour = 4;</code>
     */
    public Builder setThursdayWorkingHour(double value) {
      
      thursdayWorkingHour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double thursday_working_hour = 4;</code>
     */
    public Builder clearThursdayWorkingHour() {
      
      thursdayWorkingHour_ = 0D;
      onChanged();
      return this;
    }

    private double fridayWorkingHour_ ;
    /**
     * <code>double friday_working_hour = 5;</code>
     */
    public double getFridayWorkingHour() {
      return fridayWorkingHour_;
    }
    /**
     * <code>double friday_working_hour = 5;</code>
     */
    public Builder setFridayWorkingHour(double value) {
      
      fridayWorkingHour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double friday_working_hour = 5;</code>
     */
    public Builder clearFridayWorkingHour() {
      
      fridayWorkingHour_ = 0D;
      onChanged();
      return this;
    }

    private int dayCount_ ;
    /**
     * <code>int32 dayCount = 6;</code>
     */
    public int getDayCount() {
      return dayCount_;
    }
    /**
     * <code>int32 dayCount = 6;</code>
     */
    public Builder setDayCount(int value) {
      
      dayCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dayCount = 6;</code>
     */
    public Builder clearDayCount() {
      
      dayCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:office_service.WeeklyWorkingHourRequest)
  }

  // @@protoc_insertion_point(class_scope:office_service.WeeklyWorkingHourRequest)
  private static final grpc.services.hr_department_service.WeeklyWorkingHourRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.hr_department_service.WeeklyWorkingHourRequest();
  }

  public static grpc.services.hr_department_service.WeeklyWorkingHourRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeeklyWorkingHourRequest>
      PARSER = new com.google.protobuf.AbstractParser<WeeklyWorkingHourRequest>() {
    @java.lang.Override
    public WeeklyWorkingHourRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeeklyWorkingHourRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeeklyWorkingHourRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeeklyWorkingHourRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.hr_department_service.WeeklyWorkingHourRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

