// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

/**
 * Protobuf type {@code office_service.WeeklyWorkingHourResponse}
 */
public  final class WeeklyWorkingHourResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:office_service.WeeklyWorkingHourResponse)
    WeeklyWorkingHourResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeeklyWorkingHourResponse.newBuilder() to construct.
  private WeeklyWorkingHourResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeeklyWorkingHourResponse() {
    totalWeeklyWorkingHour_ = 0;
    weeklyWorkingHourMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeeklyWorkingHourResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            totalWeeklyWorkingHour_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            weeklyWorkingHourMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.hr_department_service.WeeklyWorkingHourResponse.class, grpc.services.hr_department_service.WeeklyWorkingHourResponse.Builder.class);
  }

  public static final int TOTAL_WEEKLY_WORKING_HOUR_FIELD_NUMBER = 1;
  private int totalWeeklyWorkingHour_;
  /**
   * <code>int32 total_weekly_working_hour = 1;</code>
   */
  public int getTotalWeeklyWorkingHour() {
    return totalWeeklyWorkingHour_;
  }

  public static final int WEEKLY_WORKING_HOUR_MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object weeklyWorkingHourMessage_;
  /**
   * <code>string weekly_working_hour_message = 2;</code>
   */
  public java.lang.String getWeeklyWorkingHourMessage() {
    java.lang.Object ref = weeklyWorkingHourMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      weeklyWorkingHourMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string weekly_working_hour_message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getWeeklyWorkingHourMessageBytes() {
    java.lang.Object ref = weeklyWorkingHourMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      weeklyWorkingHourMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalWeeklyWorkingHour_ != 0) {
      output.writeInt32(1, totalWeeklyWorkingHour_);
    }
    if (!getWeeklyWorkingHourMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, weeklyWorkingHourMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalWeeklyWorkingHour_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, totalWeeklyWorkingHour_);
    }
    if (!getWeeklyWorkingHourMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, weeklyWorkingHourMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.hr_department_service.WeeklyWorkingHourResponse)) {
      return super.equals(obj);
    }
    grpc.services.hr_department_service.WeeklyWorkingHourResponse other = (grpc.services.hr_department_service.WeeklyWorkingHourResponse) obj;

    boolean result = true;
    result = result && (getTotalWeeklyWorkingHour()
        == other.getTotalWeeklyWorkingHour());
    result = result && getWeeklyWorkingHourMessage()
        .equals(other.getWeeklyWorkingHourMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_WEEKLY_WORKING_HOUR_FIELD_NUMBER;
    hash = (53 * hash) + getTotalWeeklyWorkingHour();
    hash = (37 * hash) + WEEKLY_WORKING_HOUR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getWeeklyWorkingHourMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.hr_department_service.WeeklyWorkingHourResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code office_service.WeeklyWorkingHourResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:office_service.WeeklyWorkingHourResponse)
      grpc.services.hr_department_service.WeeklyWorkingHourResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.hr_department_service.WeeklyWorkingHourResponse.class, grpc.services.hr_department_service.WeeklyWorkingHourResponse.Builder.class);
    }

    // Construct using grpc.services.hr_department_service.WeeklyWorkingHourResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      totalWeeklyWorkingHour_ = 0;

      weeklyWorkingHourMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.hr_department_service.HRDepartmentServiceImpl.internal_static_office_service_WeeklyWorkingHourResponse_descriptor;
    }

    @java.lang.Override
    public grpc.services.hr_department_service.WeeklyWorkingHourResponse getDefaultInstanceForType() {
      return grpc.services.hr_department_service.WeeklyWorkingHourResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.hr_department_service.WeeklyWorkingHourResponse build() {
      grpc.services.hr_department_service.WeeklyWorkingHourResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.hr_department_service.WeeklyWorkingHourResponse buildPartial() {
      grpc.services.hr_department_service.WeeklyWorkingHourResponse result = new grpc.services.hr_department_service.WeeklyWorkingHourResponse(this);
      result.totalWeeklyWorkingHour_ = totalWeeklyWorkingHour_;
      result.weeklyWorkingHourMessage_ = weeklyWorkingHourMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.hr_department_service.WeeklyWorkingHourResponse) {
        return mergeFrom((grpc.services.hr_department_service.WeeklyWorkingHourResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.hr_department_service.WeeklyWorkingHourResponse other) {
      if (other == grpc.services.hr_department_service.WeeklyWorkingHourResponse.getDefaultInstance()) return this;
      if (other.getTotalWeeklyWorkingHour() != 0) {
        setTotalWeeklyWorkingHour(other.getTotalWeeklyWorkingHour());
      }
      if (!other.getWeeklyWorkingHourMessage().isEmpty()) {
        weeklyWorkingHourMessage_ = other.weeklyWorkingHourMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.hr_department_service.WeeklyWorkingHourResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.hr_department_service.WeeklyWorkingHourResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int totalWeeklyWorkingHour_ ;
    /**
     * <code>int32 total_weekly_working_hour = 1;</code>
     */
    public int getTotalWeeklyWorkingHour() {
      return totalWeeklyWorkingHour_;
    }
    /**
     * <code>int32 total_weekly_working_hour = 1;</code>
     */
    public Builder setTotalWeeklyWorkingHour(int value) {
      
      totalWeeklyWorkingHour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_weekly_working_hour = 1;</code>
     */
    public Builder clearTotalWeeklyWorkingHour() {
      
      totalWeeklyWorkingHour_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object weeklyWorkingHourMessage_ = "";
    /**
     * <code>string weekly_working_hour_message = 2;</code>
     */
    public java.lang.String getWeeklyWorkingHourMessage() {
      java.lang.Object ref = weeklyWorkingHourMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weeklyWorkingHourMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string weekly_working_hour_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWeeklyWorkingHourMessageBytes() {
      java.lang.Object ref = weeklyWorkingHourMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weeklyWorkingHourMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string weekly_working_hour_message = 2;</code>
     */
    public Builder setWeeklyWorkingHourMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      weeklyWorkingHourMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string weekly_working_hour_message = 2;</code>
     */
    public Builder clearWeeklyWorkingHourMessage() {
      
      weeklyWorkingHourMessage_ = getDefaultInstance().getWeeklyWorkingHourMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string weekly_working_hour_message = 2;</code>
     */
    public Builder setWeeklyWorkingHourMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      weeklyWorkingHourMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:office_service.WeeklyWorkingHourResponse)
  }

  // @@protoc_insertion_point(class_scope:office_service.WeeklyWorkingHourResponse)
  private static final grpc.services.hr_department_service.WeeklyWorkingHourResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.hr_department_service.WeeklyWorkingHourResponse();
  }

  public static grpc.services.hr_department_service.WeeklyWorkingHourResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeeklyWorkingHourResponse>
      PARSER = new com.google.protobuf.AbstractParser<WeeklyWorkingHourResponse>() {
    @java.lang.Override
    public WeeklyWorkingHourResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeeklyWorkingHourResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeeklyWorkingHourResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeeklyWorkingHourResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.hr_department_service.WeeklyWorkingHourResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

