// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

public interface WeeklyWorkingHourRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.WeeklyWorkingHourRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 monday_working_hour = 1;</code>
   */
  int getMondayWorkingHour();

  /**
   * <code>int32 tuesday_working_hour = 2;</code>
   */
  int getTuesdayWorkingHour();

  /**
   * <code>int32 wednesday_working_hour = 3;</code>
   */
  int getWednesdayWorkingHour();

  /**
   * <code>int32 thursday_working_hour = 4;</code>
   */
  int getThursdayWorkingHour();

  /**
   * <code>int32 friday_working_hour = 5;</code>
   */
  int getFridayWorkingHour();
}
