// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HRDepartmentService.proto

package grpc.services.hr_department_service;

public interface WeeklyWorkingHourResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.WeeklyWorkingHourResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double total_weekly_working_hour = 1;</code>
   */
  double getTotalWeeklyWorkingHour();

  /**
   * <code>string weekly_working_hour_message = 2;</code>
   */
  java.lang.String getWeeklyWorkingHourMessage();
  /**
   * <code>string weekly_working_hour_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getWeeklyWorkingHourMessageBytes();
}
