// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payroll_Year_End.proto

package grpc.services.payroll_year_end;

public final class PayrollYearEndServiceImpl {
  private PayrollYearEndServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_PayrollYearEndRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_PayrollYearEndRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_PayrollYearEndResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_PayrollYearEndResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026Payroll_Year_End.proto\022\016office_service" +
      "\"\'\n\025PayrollYearEndRequest\022\016\n\006length\030\001 \001(" +
      "\005\"%\n\026PayrollYearEndResponse\022\013\n\003val\030\001 \001(\t" +
      "2v\n\025PayrollYearEndService\022]\n\ninput_hour\022" +
      "%.office_service.PayrollYearEndRequest\032&" +
      ".office_service.PayrollYearEndResponse(\001" +
      "B=\n\036grpc.services.payroll_year_endB\031Payr" +
      "ollYearEndServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_service_PayrollYearEndRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_service_PayrollYearEndRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_PayrollYearEndRequest_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_office_service_PayrollYearEndResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_service_PayrollYearEndResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_PayrollYearEndResponse_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
