// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payroll_Year_End.proto

package grpc.services.payroll_year_end;

public interface PayrollYearEndResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.PayrollYearEndResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
