// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payroll_Year_End.proto

package grpc.services.payroll_year_end;

public interface PayrollYearEndRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.PayrollYearEndRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
