// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sales_Department_Service.proto

package grpc.services.sales_department_service;

public final class HRDepartmentServiceImpl {
  private HRDepartmentServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_Stock_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_Stock_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_Stock_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_Stock_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_Order_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_Order_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_Order_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_Order_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036Sales_Department_Service.proto\022\016office" +
      "_service\"&\n\rStock_Request\022\025\n\rstock_reque" +
      "st\030\001 \001(\t\"(\n\016Stock_Response\022\026\n\016Stock_resp" +
      "onse\030\001 \001(\t\"V\n\rOrder_Request\022\025\n\rdelivery_" +
      "area\030\001 \001(\t\022\024\n\014product_name\030\002 \001(\t\022\030\n\020prod" +
      "uct_quantity\030\003 \001(\005\"L\n\016Order_Response\022\036\n\026" +
      "order_response_message\030\001 \001(\t\022\032\n\022order_co" +
      "nfirmation\030\002 \001(\t2\303\001\n\026SalesDepartmentServ" +
      "ice\022N\n\013check_stock\022\035.office_service.Stoc" +
      "k_Request\032\036.office_service.Stock_Respons" +
      "e\"\000\022Y\n\022order_confirmation\022\035.office_servi" +
      "ce.Order_Request\032\036.office_service.Order_" +
      "Response\"\000(\0010\001BC\n&grpc.services.sales_de" +
      "partment_serviceB\027HRDepartmentServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_service_Stock_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_service_Stock_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_Stock_Request_descriptor,
        new java.lang.String[] { "StockRequest", });
    internal_static_office_service_Stock_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_service_Stock_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_Stock_Response_descriptor,
        new java.lang.String[] { "StockResponse", });
    internal_static_office_service_Order_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_office_service_Order_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_Order_Request_descriptor,
        new java.lang.String[] { "DeliveryArea", "ProductName", "ProductQuantity", });
    internal_static_office_service_Order_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_office_service_Order_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_Order_Response_descriptor,
        new java.lang.String[] { "OrderResponseMessage", "OrderConfirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
