// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sales_Department_Service.proto

package grpc.services.sales_department_service;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string delivery_area = 1;</code>
   */
  java.lang.String getDeliveryArea();
  /**
   * <code>string delivery_area = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeliveryAreaBytes();

  /**
   * <code>string product_name = 2;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>int32 product_quantity = 3;</code>
   */
  int getProductQuantity();
}
