// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sales_Department_Service.proto

package grpc.services.sales_department_service;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_response_message = 1;</code>
   */
  java.lang.String getOrderResponseMessage();
  /**
   * <code>string order_response_message = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderResponseMessageBytes();

  /**
   * <code>string order_confirmation = 2;</code>
   */
  java.lang.String getOrderConfirmation();
  /**
   * <code>string order_confirmation = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderConfirmationBytes();
}
