// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sales_Department_Service.proto

package grpc.services.sales_department_service;

/**
 * Protobuf type {@code office_service.OrderResponse}
 */
public  final class OrderResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:office_service.OrderResponse)
    OrderResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderResponse.newBuilder() to construct.
  private OrderResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderResponse() {
    orderResponseMessage_ = "";
    remainingQuantityAfterOrderMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            orderResponseMessage_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            remainingQuantityAfterOrderMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.sales_department_service.SalesDepartmentServiceImpl.internal_static_office_service_OrderResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.sales_department_service.SalesDepartmentServiceImpl.internal_static_office_service_OrderResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.sales_department_service.OrderResponse.class, grpc.services.sales_department_service.OrderResponse.Builder.class);
  }

  public static final int ORDER_RESPONSE_MESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object orderResponseMessage_;
  /**
   * <code>string order_response_message = 1;</code>
   */
  public java.lang.String getOrderResponseMessage() {
    java.lang.Object ref = orderResponseMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderResponseMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string order_response_message = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOrderResponseMessageBytes() {
    java.lang.Object ref = orderResponseMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderResponseMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMAINING_QUANTITY_AFTER_ORDER_MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object remainingQuantityAfterOrderMessage_;
  /**
   * <code>string remaining_quantity_after_order_message = 2;</code>
   */
  public java.lang.String getRemainingQuantityAfterOrderMessage() {
    java.lang.Object ref = remainingQuantityAfterOrderMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      remainingQuantityAfterOrderMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string remaining_quantity_after_order_message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRemainingQuantityAfterOrderMessageBytes() {
    java.lang.Object ref = remainingQuantityAfterOrderMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      remainingQuantityAfterOrderMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOrderResponseMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderResponseMessage_);
    }
    if (!getRemainingQuantityAfterOrderMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, remainingQuantityAfterOrderMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOrderResponseMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderResponseMessage_);
    }
    if (!getRemainingQuantityAfterOrderMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, remainingQuantityAfterOrderMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.sales_department_service.OrderResponse)) {
      return super.equals(obj);
    }
    grpc.services.sales_department_service.OrderResponse other = (grpc.services.sales_department_service.OrderResponse) obj;

    boolean result = true;
    result = result && getOrderResponseMessage()
        .equals(other.getOrderResponseMessage());
    result = result && getRemainingQuantityAfterOrderMessage()
        .equals(other.getRemainingQuantityAfterOrderMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORDER_RESPONSE_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getOrderResponseMessage().hashCode();
    hash = (37 * hash) + REMAINING_QUANTITY_AFTER_ORDER_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getRemainingQuantityAfterOrderMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.sales_department_service.OrderResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.sales_department_service.OrderResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.sales_department_service.OrderResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.sales_department_service.OrderResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.sales_department_service.OrderResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.sales_department_service.OrderResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.sales_department_service.OrderResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.sales_department_service.OrderResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.sales_department_service.OrderResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.sales_department_service.OrderResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.sales_department_service.OrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.sales_department_service.OrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.sales_department_service.OrderResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code office_service.OrderResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:office_service.OrderResponse)
      grpc.services.sales_department_service.OrderResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.sales_department_service.SalesDepartmentServiceImpl.internal_static_office_service_OrderResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.sales_department_service.SalesDepartmentServiceImpl.internal_static_office_service_OrderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.sales_department_service.OrderResponse.class, grpc.services.sales_department_service.OrderResponse.Builder.class);
    }

    // Construct using grpc.services.sales_department_service.OrderResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      orderResponseMessage_ = "";

      remainingQuantityAfterOrderMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.sales_department_service.SalesDepartmentServiceImpl.internal_static_office_service_OrderResponse_descriptor;
    }

    @java.lang.Override
    public grpc.services.sales_department_service.OrderResponse getDefaultInstanceForType() {
      return grpc.services.sales_department_service.OrderResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.sales_department_service.OrderResponse build() {
      grpc.services.sales_department_service.OrderResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.sales_department_service.OrderResponse buildPartial() {
      grpc.services.sales_department_service.OrderResponse result = new grpc.services.sales_department_service.OrderResponse(this);
      result.orderResponseMessage_ = orderResponseMessage_;
      result.remainingQuantityAfterOrderMessage_ = remainingQuantityAfterOrderMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.sales_department_service.OrderResponse) {
        return mergeFrom((grpc.services.sales_department_service.OrderResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.sales_department_service.OrderResponse other) {
      if (other == grpc.services.sales_department_service.OrderResponse.getDefaultInstance()) return this;
      if (!other.getOrderResponseMessage().isEmpty()) {
        orderResponseMessage_ = other.orderResponseMessage_;
        onChanged();
      }
      if (!other.getRemainingQuantityAfterOrderMessage().isEmpty()) {
        remainingQuantityAfterOrderMessage_ = other.remainingQuantityAfterOrderMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.sales_department_service.OrderResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.sales_department_service.OrderResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object orderResponseMessage_ = "";
    /**
     * <code>string order_response_message = 1;</code>
     */
    public java.lang.String getOrderResponseMessage() {
      java.lang.Object ref = orderResponseMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderResponseMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string order_response_message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderResponseMessageBytes() {
      java.lang.Object ref = orderResponseMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderResponseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string order_response_message = 1;</code>
     */
    public Builder setOrderResponseMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderResponseMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string order_response_message = 1;</code>
     */
    public Builder clearOrderResponseMessage() {
      
      orderResponseMessage_ = getDefaultInstance().getOrderResponseMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string order_response_message = 1;</code>
     */
    public Builder setOrderResponseMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderResponseMessage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object remainingQuantityAfterOrderMessage_ = "";
    /**
     * <code>string remaining_quantity_after_order_message = 2;</code>
     */
    public java.lang.String getRemainingQuantityAfterOrderMessage() {
      java.lang.Object ref = remainingQuantityAfterOrderMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remainingQuantityAfterOrderMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string remaining_quantity_after_order_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRemainingQuantityAfterOrderMessageBytes() {
      java.lang.Object ref = remainingQuantityAfterOrderMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remainingQuantityAfterOrderMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string remaining_quantity_after_order_message = 2;</code>
     */
    public Builder setRemainingQuantityAfterOrderMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      remainingQuantityAfterOrderMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string remaining_quantity_after_order_message = 2;</code>
     */
    public Builder clearRemainingQuantityAfterOrderMessage() {
      
      remainingQuantityAfterOrderMessage_ = getDefaultInstance().getRemainingQuantityAfterOrderMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string remaining_quantity_after_order_message = 2;</code>
     */
    public Builder setRemainingQuantityAfterOrderMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      remainingQuantityAfterOrderMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:office_service.OrderResponse)
  }

  // @@protoc_insertion_point(class_scope:office_service.OrderResponse)
  private static final grpc.services.sales_department_service.OrderResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.sales_department_service.OrderResponse();
  }

  public static grpc.services.sales_department_service.OrderResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderResponse>
      PARSER = new com.google.protobuf.AbstractParser<OrderResponse>() {
    @java.lang.Override
    public OrderResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.sales_department_service.OrderResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

