// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sales_Department_Service.proto

package grpc.services.sales_department_service;

public final class SalesDepartmentServiceImpl {
  private SalesDepartmentServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_StockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_StockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_OrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036Sales_Department_Service.proto\022\016office" +
      "_service\"y\n\014StockRequest\022&\n\036stock_reques" +
      "t_product_quantity\030\001 \001(\005\022\"\n\032stock_reques" +
      "t_product_type\030\002 \001(\t\022\035\n\025stock_request_me" +
      "ssage\030\003 \001(\t\"X\n\rStockResponse\022\'\n\037stock_re" +
      "sponse_product_quantity\030\001 \001(\005\022\036\n\026Stock_r" +
      "esponse_message\030\002 \001(\t\"m\n\014OrderRequest\022\025\n" +
      "\rdelivery_area\030\001 \001(\t\022\024\n\014product_name\030\002 \001" +
      "(\t\022\030\n\020product_quantity\030\003 \001(\005\022\026\n\016set_fiel" +
      "d_name\030\004 \001(\005\"_\n\rOrderResponse\022\036\n\026order_r" +
      "esponse_message\030\001 \001(\t\022.\n&remaining_quant" +
      "ity_after_order_message\030\002 \001(\t2\275\001\n\026SalesD" +
      "epartmentService\022K\n\ncheckStock\022\034.office_" +
      "service.StockRequest\032\035.office_service.St" +
      "ockResponse\"\000\022V\n\021orderConfirmation\022\034.off" +
      "ice_service.OrderRequest\032\035.office_servic" +
      "e.OrderResponse\"\000(\0010\001BF\n&grpc.services.s" +
      "ales_department_serviceB\032SalesDepartment" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_service_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_service_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_StockRequest_descriptor,
        new java.lang.String[] { "StockRequestProductQuantity", "StockRequestProductType", "StockRequestMessage", });
    internal_static_office_service_StockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_service_StockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_StockResponse_descriptor,
        new java.lang.String[] { "StockResponseProductQuantity", "StockResponseMessage", });
    internal_static_office_service_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_office_service_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_OrderRequest_descriptor,
        new java.lang.String[] { "DeliveryArea", "ProductName", "ProductQuantity", "SetFieldName", });
    internal_static_office_service_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_office_service_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_OrderResponse_descriptor,
        new java.lang.String[] { "OrderResponseMessage", "RemainingQuantityAfterOrderMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
