// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sales_Department_Service.proto

package grpc.services.sales_department_service;

public interface Stock_RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.Stock_Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stock_request = 1;</code>
   */
  java.lang.String getStockRequest();
  /**
   * <code>string stock_request = 1;</code>
   */
  com.google.protobuf.ByteString
      getStockRequestBytes();
}
