// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sales_Department_Service.proto

package grpc.services.sales_department_service;

public interface Stock_ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.Stock_Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Stock_response = 1;</code>
   */
  java.lang.String getStockResponse();
  /**
   * <code>string Stock_response = 1;</code>
   */
  com.google.protobuf.ByteString
      getStockResponseBytes();
}
