// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sales_Department_Service.proto

package grpc.services.sales_department_service;

public interface StockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.StockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stock_request_product_quantity = 1;</code>
   */
  int getStockRequestProductQuantity();

  /**
   * <code>string stock_request_product_type = 2;</code>
   */
  java.lang.String getStockRequestProductType();
  /**
   * <code>string stock_request_product_type = 2;</code>
   */
  com.google.protobuf.ByteString
      getStockRequestProductTypeBytes();

  /**
   * <code>string stock_request_message = 3;</code>
   */
  java.lang.String getStockRequestMessage();
  /**
   * <code>string stock_request_message = 3;</code>
   */
  com.google.protobuf.ByteString
      getStockRequestMessageBytes();
}
