// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sales_Department_Service.proto

package grpc.services.sales_department_service;

public interface StockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.StockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stock_response_product_quantity = 1;</code>
   */
  int getStockResponseProductQuantity();

  /**
   * <code>string Stock_response_message = 2;</code>
   */
  java.lang.String getStockResponseMessage();
  /**
   * <code>string Stock_response_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getStockResponseMessageBytes();
}
