// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

/**
 * Protobuf type {@code office_service.AvailableSeatResponse}
 */
public  final class AvailableSeatResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:office_service.AvailableSeatResponse)
    AvailableSeatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AvailableSeatResponse.newBuilder() to construct.
  private AvailableSeatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AvailableSeatResponse() {
    availableSeatResponse_ = 0;
    availableSeatResponseMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AvailableSeatResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            availableSeatResponse_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            availableSeatResponseMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_AvailableSeatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_AvailableSeatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.reserve_seat.AvailableSeatResponse.class, grpc.services.reserve_seat.AvailableSeatResponse.Builder.class);
  }

  public static final int AVAILABLE_SEAT_RESPONSE_FIELD_NUMBER = 1;
  private int availableSeatResponse_;
  /**
   * <code>int32 available_seat_response = 1;</code>
   */
  public int getAvailableSeatResponse() {
    return availableSeatResponse_;
  }

  public static final int AVAILABLE_SEAT_RESPONSE_MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object availableSeatResponseMessage_;
  /**
   * <code>string available_seat_response_message = 2;</code>
   */
  public java.lang.String getAvailableSeatResponseMessage() {
    java.lang.Object ref = availableSeatResponseMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      availableSeatResponseMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string available_seat_response_message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAvailableSeatResponseMessageBytes() {
    java.lang.Object ref = availableSeatResponseMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      availableSeatResponseMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (availableSeatResponse_ != 0) {
      output.writeInt32(1, availableSeatResponse_);
    }
    if (!getAvailableSeatResponseMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, availableSeatResponseMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (availableSeatResponse_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, availableSeatResponse_);
    }
    if (!getAvailableSeatResponseMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, availableSeatResponseMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.reserve_seat.AvailableSeatResponse)) {
      return super.equals(obj);
    }
    grpc.services.reserve_seat.AvailableSeatResponse other = (grpc.services.reserve_seat.AvailableSeatResponse) obj;

    boolean result = true;
    result = result && (getAvailableSeatResponse()
        == other.getAvailableSeatResponse());
    result = result && getAvailableSeatResponseMessage()
        .equals(other.getAvailableSeatResponseMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AVAILABLE_SEAT_RESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + getAvailableSeatResponse();
    hash = (37 * hash) + AVAILABLE_SEAT_RESPONSE_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getAvailableSeatResponseMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.reserve_seat.AvailableSeatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.reserve_seat.AvailableSeatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code office_service.AvailableSeatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:office_service.AvailableSeatResponse)
      grpc.services.reserve_seat.AvailableSeatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_AvailableSeatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_AvailableSeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.reserve_seat.AvailableSeatResponse.class, grpc.services.reserve_seat.AvailableSeatResponse.Builder.class);
    }

    // Construct using grpc.services.reserve_seat.AvailableSeatResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      availableSeatResponse_ = 0;

      availableSeatResponseMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_AvailableSeatResponse_descriptor;
    }

    @java.lang.Override
    public grpc.services.reserve_seat.AvailableSeatResponse getDefaultInstanceForType() {
      return grpc.services.reserve_seat.AvailableSeatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.reserve_seat.AvailableSeatResponse build() {
      grpc.services.reserve_seat.AvailableSeatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.reserve_seat.AvailableSeatResponse buildPartial() {
      grpc.services.reserve_seat.AvailableSeatResponse result = new grpc.services.reserve_seat.AvailableSeatResponse(this);
      result.availableSeatResponse_ = availableSeatResponse_;
      result.availableSeatResponseMessage_ = availableSeatResponseMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.reserve_seat.AvailableSeatResponse) {
        return mergeFrom((grpc.services.reserve_seat.AvailableSeatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.reserve_seat.AvailableSeatResponse other) {
      if (other == grpc.services.reserve_seat.AvailableSeatResponse.getDefaultInstance()) return this;
      if (other.getAvailableSeatResponse() != 0) {
        setAvailableSeatResponse(other.getAvailableSeatResponse());
      }
      if (!other.getAvailableSeatResponseMessage().isEmpty()) {
        availableSeatResponseMessage_ = other.availableSeatResponseMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.reserve_seat.AvailableSeatResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.reserve_seat.AvailableSeatResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int availableSeatResponse_ ;
    /**
     * <code>int32 available_seat_response = 1;</code>
     */
    public int getAvailableSeatResponse() {
      return availableSeatResponse_;
    }
    /**
     * <code>int32 available_seat_response = 1;</code>
     */
    public Builder setAvailableSeatResponse(int value) {
      
      availableSeatResponse_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 available_seat_response = 1;</code>
     */
    public Builder clearAvailableSeatResponse() {
      
      availableSeatResponse_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object availableSeatResponseMessage_ = "";
    /**
     * <code>string available_seat_response_message = 2;</code>
     */
    public java.lang.String getAvailableSeatResponseMessage() {
      java.lang.Object ref = availableSeatResponseMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        availableSeatResponseMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string available_seat_response_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAvailableSeatResponseMessageBytes() {
      java.lang.Object ref = availableSeatResponseMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        availableSeatResponseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string available_seat_response_message = 2;</code>
     */
    public Builder setAvailableSeatResponseMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      availableSeatResponseMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string available_seat_response_message = 2;</code>
     */
    public Builder clearAvailableSeatResponseMessage() {
      
      availableSeatResponseMessage_ = getDefaultInstance().getAvailableSeatResponseMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string available_seat_response_message = 2;</code>
     */
    public Builder setAvailableSeatResponseMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      availableSeatResponseMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:office_service.AvailableSeatResponse)
  }

  // @@protoc_insertion_point(class_scope:office_service.AvailableSeatResponse)
  private static final grpc.services.reserve_seat.AvailableSeatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.reserve_seat.AvailableSeatResponse();
  }

  public static grpc.services.reserve_seat.AvailableSeatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AvailableSeatResponse>
      PARSER = new com.google.protobuf.AbstractParser<AvailableSeatResponse>() {
    @java.lang.Override
    public AvailableSeatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AvailableSeatResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AvailableSeatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AvailableSeatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.reserve_seat.AvailableSeatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

