// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public interface AvailableSeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.AvailableSeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 available_seat_request = 1;</code>
   */
  int getAvailableSeatRequest();
}
