// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public interface AvailableSeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.AvailableSeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 available_seat_response = 1;</code>
   */
  int getAvailableSeatResponse();

  /**
   * <code>string available_seat_response_message = 2;</code>
   */
  java.lang.String getAvailableSeatResponseMessage();
  /**
   * <code>string available_seat_response_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getAvailableSeatResponseMessageBytes();
}
