// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.Empty)
    com.google.protobuf.MessageOrBuilder {
}
