// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.office_service.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.office_service.Message.Enum detail = 1;</code>
   */
  grpc.services.reserve_seat.Message.Enum getDetail();
}
