// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public interface NoSameSeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.NoSameSeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string no_same_seat_message = 2;</code>
   */
  java.lang.String getNoSameSeatMessage();
  /**
   * <code>string no_same_seat_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getNoSameSeatMessageBytes();
}
