// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public interface NoSameSeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.NoSameSeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 same_seat_number = 1;</code>
   */
  int getSameSeatNumber();
}
