// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

/**
 * Protobuf type {@code office_service.NoSameSeatResponse}
 */
public  final class NoSameSeatResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:office_service.NoSameSeatResponse)
    NoSameSeatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NoSameSeatResponse.newBuilder() to construct.
  private NoSameSeatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NoSameSeatResponse() {
    noSameSeatMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NoSameSeatResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            noSameSeatMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_NoSameSeatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_NoSameSeatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.reserve_seat.NoSameSeatResponse.class, grpc.services.reserve_seat.NoSameSeatResponse.Builder.class);
  }

  public static final int NO_SAME_SEAT_MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object noSameSeatMessage_;
  /**
   * <code>string no_same_seat_message = 2;</code>
   */
  public java.lang.String getNoSameSeatMessage() {
    java.lang.Object ref = noSameSeatMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      noSameSeatMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string no_same_seat_message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNoSameSeatMessageBytes() {
    java.lang.Object ref = noSameSeatMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      noSameSeatMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNoSameSeatMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, noSameSeatMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNoSameSeatMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, noSameSeatMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.reserve_seat.NoSameSeatResponse)) {
      return super.equals(obj);
    }
    grpc.services.reserve_seat.NoSameSeatResponse other = (grpc.services.reserve_seat.NoSameSeatResponse) obj;

    boolean result = true;
    result = result && getNoSameSeatMessage()
        .equals(other.getNoSameSeatMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NO_SAME_SEAT_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getNoSameSeatMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.reserve_seat.NoSameSeatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.reserve_seat.NoSameSeatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code office_service.NoSameSeatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:office_service.NoSameSeatResponse)
      grpc.services.reserve_seat.NoSameSeatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_NoSameSeatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_NoSameSeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.reserve_seat.NoSameSeatResponse.class, grpc.services.reserve_seat.NoSameSeatResponse.Builder.class);
    }

    // Construct using grpc.services.reserve_seat.NoSameSeatResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      noSameSeatMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.reserve_seat.ReserveSeatServiceImpl.internal_static_office_service_NoSameSeatResponse_descriptor;
    }

    @java.lang.Override
    public grpc.services.reserve_seat.NoSameSeatResponse getDefaultInstanceForType() {
      return grpc.services.reserve_seat.NoSameSeatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.reserve_seat.NoSameSeatResponse build() {
      grpc.services.reserve_seat.NoSameSeatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.reserve_seat.NoSameSeatResponse buildPartial() {
      grpc.services.reserve_seat.NoSameSeatResponse result = new grpc.services.reserve_seat.NoSameSeatResponse(this);
      result.noSameSeatMessage_ = noSameSeatMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.reserve_seat.NoSameSeatResponse) {
        return mergeFrom((grpc.services.reserve_seat.NoSameSeatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.reserve_seat.NoSameSeatResponse other) {
      if (other == grpc.services.reserve_seat.NoSameSeatResponse.getDefaultInstance()) return this;
      if (!other.getNoSameSeatMessage().isEmpty()) {
        noSameSeatMessage_ = other.noSameSeatMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.reserve_seat.NoSameSeatResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.reserve_seat.NoSameSeatResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object noSameSeatMessage_ = "";
    /**
     * <code>string no_same_seat_message = 2;</code>
     */
    public java.lang.String getNoSameSeatMessage() {
      java.lang.Object ref = noSameSeatMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        noSameSeatMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string no_same_seat_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNoSameSeatMessageBytes() {
      java.lang.Object ref = noSameSeatMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        noSameSeatMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string no_same_seat_message = 2;</code>
     */
    public Builder setNoSameSeatMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      noSameSeatMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string no_same_seat_message = 2;</code>
     */
    public Builder clearNoSameSeatMessage() {
      
      noSameSeatMessage_ = getDefaultInstance().getNoSameSeatMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string no_same_seat_message = 2;</code>
     */
    public Builder setNoSameSeatMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      noSameSeatMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:office_service.NoSameSeatResponse)
  }

  // @@protoc_insertion_point(class_scope:office_service.NoSameSeatResponse)
  private static final grpc.services.reserve_seat.NoSameSeatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.reserve_seat.NoSameSeatResponse();
  }

  public static grpc.services.reserve_seat.NoSameSeatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NoSameSeatResponse>
      PARSER = new com.google.protobuf.AbstractParser<NoSameSeatResponse>() {
    @java.lang.Override
    public NoSameSeatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NoSameSeatResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NoSameSeatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NoSameSeatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.reserve_seat.NoSameSeatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

