// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public interface ReserveSeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.ReserveSeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reserve_seat_response = 1;</code>
   */
  int getReserveSeatResponse();

  /**
   * <code>string reserve_seat_response_message = 2;</code>
   */
  java.lang.String getReserveSeatResponseMessage();
  /**
   * <code>string reserve_seat_response_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getReserveSeatResponseMessageBytes();
}
