// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public interface ReserveSeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.ReserveSeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reserve_seat_request = 1;</code>
   */
  int getReserveSeatRequest();
}
