// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public interface ReserveSeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.ReserveSeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 seat_number = 1;</code>
   */
  int getSeatNumber();

  /**
   * <code>int32 seat_number_min = 2;</code>
   */
  int getSeatNumberMin();

  /**
   * <code>int32 seat_number_max = 3;</code>
   */
  int getSeatNumberMax();
}
