// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public final class ReserveSeatServiceImpl {
  private ReserveSeatServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_ReserveSeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_ReserveSeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_ReserveSeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_ReserveSeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_AvailableSeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_AvailableSeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_AvailableSeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_AvailableSeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Reserve_Seat.proto\022\016office_service\"2\n\022" +
      "ReserveSeatRequest\022\034\n\024reserve_seat_reque" +
      "st\030\001 \001(\005\"[\n\023ReserveSeatResponse\022\035\n\025reser" +
      "ve_seat_response\030\001 \001(\005\022%\n\035reserve_seat_r" +
      "esponse_message\030\002 \001(\t\"6\n\024AvailableSeatRe" +
      "quest\022\036\n\026available_seat_request\030\001 \001(\005\"a\n" +
      "\025AvailableSeatResponse\022\037\n\027available_seat" +
      "_response\030\001 \001(\005\022\'\n\037available_seat_respon" +
      "se_message\030\002 \001(\t2\320\001\n\022ReserveSeatService\022" +
      "`\n\ravailableSeat\022$.office_service.Availa" +
      "bleSeatRequest\032%.office_service.Availabl" +
      "eSeatResponse\"\0000\001\022X\n\013reserveSeat\022\".offic" +
      "e_service.ReserveSeatRequest\032#.office_se" +
      "rvice.ReserveSeatResponse\"\000B6\n\032grpc.serv" +
      "ices.reserve_seatB\026ReserveSeatServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_service_ReserveSeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_service_ReserveSeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_ReserveSeatRequest_descriptor,
        new java.lang.String[] { "ReserveSeatRequest", });
    internal_static_office_service_ReserveSeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_service_ReserveSeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_ReserveSeatResponse_descriptor,
        new java.lang.String[] { "ReserveSeatResponse", "ReserveSeatResponseMessage", });
    internal_static_office_service_AvailableSeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_office_service_AvailableSeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_AvailableSeatRequest_descriptor,
        new java.lang.String[] { "AvailableSeatRequest", });
    internal_static_office_service_AvailableSeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_office_service_AvailableSeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_AvailableSeatResponse_descriptor,
        new java.lang.String[] { "AvailableSeatResponse", "AvailableSeatResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
