// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserve_Seat.proto

package grpc.services.reserve_seat;

public final class ReserveSeatServiceImpl {
  private ReserveSeatServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_ReserveSeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_ReserveSeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_ReserveSeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_ReserveSeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_NoSameSeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_NoSameSeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_NoSameSeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_NoSameSeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Reserve_Seat.proto\022\016office_service\")\n\022" +
      "ReserveSeatRequest\022\023\n\013seat_number\030\001 \001(\005\"" +
      "\\\n\023ReserveSeatResponse\022\023\n\013seat_number\030\001 " +
      "\001(\005\022\027\n\017seat_number_min\030\002 \001(\005\022\027\n\017seat_num" +
      "ber_max\030\003 \001(\005\"-\n\021NoSameSeatRequest\022\030\n\020sa" +
      "me_seat_number\030\001 \001(\005\"2\n\022NoSameSeatRespon" +
      "se\022\034\n\024no_same_seat_message\030\002 \001(\t2\302\001\n\022Res" +
      "erveSeatService\022V\n\007reserve\022\".office_serv" +
      "ice.ReserveSeatRequest\032#.office_service." +
      "ReserveSeatResponse\"\0000\001\022T\n\tsame_seat\022!.o" +
      "ffice_service.NoSameSeatRequest\032\".office" +
      "_service.NoSameSeatResponse\"\000B6\n\032grpc.se" +
      "rvices.reserve_seatB\026ReserveSeatServiceI" +
      "mplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_service_ReserveSeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_service_ReserveSeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_ReserveSeatRequest_descriptor,
        new java.lang.String[] { "SeatNumber", });
    internal_static_office_service_ReserveSeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_service_ReserveSeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_ReserveSeatResponse_descriptor,
        new java.lang.String[] { "SeatNumber", "SeatNumberMin", "SeatNumberMax", });
    internal_static_office_service_NoSameSeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_office_service_NoSameSeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_NoSameSeatRequest_descriptor,
        new java.lang.String[] { "SameSeatNumber", });
    internal_static_office_service_NoSameSeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_office_service_NoSameSeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_NoSameSeatResponse_descriptor,
        new java.lang.String[] { "NoSameSeatMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
