// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weekly_Working_Hour.proto

package grpc.services.weekly_working_hour;

public final class WeeklyWorkingHourServiceImpl {
  private WeeklyWorkingHourServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_WeeklyWorkingHourRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_WeeklyWorkingHourRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_WeeklyWorkingHourResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_WeeklyWorkingHourResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Weekly_Working_Hour.proto\022\007strings\"\'\n\030" +
      "WeeklyWorkingHourRequest\022\013\n\003val\030\001 \001(\t\"(\n" +
      "\031WeeklyWorkingHourResponse\022\013\n\003val\030\001 \001(\t2" +
      "l\n\030WeeklyWorkingHourService\022P\n\005check\022!.s" +
      "trings.WeeklyWorkingHourRequest\032\".string" +
      "s.WeeklyWorkingHourResponse0\001BC\n!grpc.se" +
      "rvices.weekly_working_hourB\034WeeklyWorkin" +
      "gHourServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_strings_WeeklyWorkingHourRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_strings_WeeklyWorkingHourRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_WeeklyWorkingHourRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_strings_WeeklyWorkingHourResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_strings_WeeklyWorkingHourResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_WeeklyWorkingHourResponse_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
