// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weekly_Working_Hour.proto

package grpc.services.weekly_working_hour;

public interface WeeklyWorkingHourRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.WeeklyWorkingHourRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
