// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weekly_Working_Hour.proto

package grpc.services.weekly_working_hour;

public final class WeeklyWorkingHourServiceImpl {
  private WeeklyWorkingHourServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_WeeklyWorkingHourRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_WeeklyWorkingHourRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_WeeklyWorkingHourResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_WeeklyWorkingHourResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Weekly_Working_Hour.proto\022\016office_serv" +
      "ice\"\'\n\030WeeklyWorkingHourRequest\022\013\n\003val\030\001" +
      " \001(\t\"(\n\031WeeklyWorkingHourResponse\022\013\n\003val" +
      "\030\001 \001(\t2z\n\030WeeklyWorkingHourService\022^\n\005ch" +
      "eck\022(.office_service.WeeklyWorkingHourRe" +
      "quest\032).office_service.WeeklyWorkingHour" +
      "Response0\001BC\n!grpc.services.weekly_worki" +
      "ng_hourB\034WeeklyWorkingHourServiceImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_service_WeeklyWorkingHourRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_service_WeeklyWorkingHourRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_WeeklyWorkingHourRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_office_service_WeeklyWorkingHourResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_service_WeeklyWorkingHourResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_WeeklyWorkingHourResponse_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
