// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order_Automation.proto

package grpc.services.order_automation;

public interface OrderAutomationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office_service.OrderAutomationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
