// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order_Automation.proto

package grpc.services.order_automation;

public final class OrderAutomationServiceImpl {
  private OrderAutomationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_OrderAutomationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_OrderAutomationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_service_OrderAutomationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_service_OrderAutomationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026Order_Automation.proto\022\016office_service" +
      "\"%\n\026OrderAutomationRequest\022\013\n\003val\030\001 \001(\t\"" +
      "&\n\027OrderAutomationResponse\022\013\n\003val\030\001 \001(\t2" +
      "x\n\026OrderAutomationService\022^\n\005order\022&.off" +
      "ice_service.OrderAutomationRequest\032\'.off" +
      "ice_service.OrderAutomationResponse\"\000(\0010" +
      "\001B>\n\036grpc.services.order_automationB\032Ord" +
      "erAutomationServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_service_OrderAutomationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_service_OrderAutomationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_OrderAutomationRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_office_service_OrderAutomationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_service_OrderAutomationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_service_OrderAutomationResponse_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
